/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/11.0.4
 * Generated at: 2026-01-06 15:26:32 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class DistributedProgramming_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <title>Distributed Programming | E-Learning</title>\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Icons -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Google Font -->\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Inter:wght@300;400;600;700&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <!-- AOS Animations -->\r\n");
      out.write("    <link href=\"https://unpkg.com/aos@2.3.1/dist/aos.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <style>\r\n");
      out.write("        * { box-sizing: border-box; }\r\n");
      out.write("        body {\r\n");
      out.write("            margin: 0;\r\n");
      out.write("            font-family: 'Inter', sans-serif;\r\n");
      out.write("            background: linear-gradient(135deg, #020617, #020617);\r\n");
      out.write("            color: #e5e7eb;\r\n");
      out.write("        }\r\n");
      out.write("        header {\r\n");
      out.write("            padding: 4rem 2rem;\r\n");
      out.write("            background: radial-gradient(circle at top, #2563eb55, transparent 60%);\r\n");
      out.write("        }\r\n");
      out.write("        header h1 {\r\n");
      out.write("            font-size: 3rem;\r\n");
      out.write("            font-weight: 700;\r\n");
      out.write("        }\r\n");
      out.write("        header p {\r\n");
      out.write("            max-width: 600px;\r\n");
      out.write("            color: #c7d2fe;\r\n");
      out.write("        }\r\n");
      out.write("        .container {\r\n");
      out.write("            max-width: 1200px;\r\n");
      out.write("            margin: auto;\r\n");
      out.write("            padding: 2rem;\r\n");
      out.write("        }\r\n");
      out.write("        .grid {\r\n");
      out.write("            display: grid;\r\n");
      out.write("            grid-template-columns: repeat(auto-fit, minmax(250px, 1fr));\r\n");
      out.write("            gap: 1.5rem;\r\n");
      out.write("        }\r\n");
      out.write("        .card {\r\n");
      out.write("            background: rgba(15, 23, 42, 0.8);\r\n");
      out.write("            border-radius: 16px;\r\n");
      out.write("            padding: 1.5rem;\r\n");
      out.write("            box-shadow: 0 20px 40px rgba(0,0,0,0.4);\r\n");
      out.write("            transition: transform .3s ease;\r\n");
      out.write("        }\r\n");
      out.write("        .card:hover { transform: translateY(-8px); }\r\n");
      out.write("        .card i {\r\n");
      out.write("            font-size: 2rem;\r\n");
      out.write("            color: #60a5fa;\r\n");
      out.write("            margin-bottom: 1rem;\r\n");
      out.write("        }\r\n");
      out.write("        h2 {\r\n");
      out.write("            font-size: 2rem;\r\n");
      out.write("            margin-bottom: 1.5rem;\r\n");
      out.write("        }\r\n");
      out.write("        footer {\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            padding: 2rem;\r\n");
      out.write("            color: #94a3b8;\r\n");
      out.write("            font-size: .9rem;\r\n");
      out.write("        }\r\n");
      out.write("        .step {\r\n");
      out.write("            background: #020617;\r\n");
      out.write("            border-left: 4px solid #3b82f6;\r\n");
      out.write("            padding: 1rem 1.5rem;\r\n");
      out.write("            border-radius: 12px;\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<header>\r\n");
      out.write("    <div class=\"container\" data-aos=\"fade-up\">\r\n");
      out.write("        <h1>Distributed Programming</h1>\r\n");
      out.write("        <p>Advanced Programming (CSE 3312) – Java RMI E-Learning Module</p>\r\n");
      out.write("    </div>\r\n");
      out.write("</header>\r\n");
      out.write("\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("    <section data-aos=\"fade-up\">\r\n");
      out.write("        <h2>Learning Objectives</h2>\r\n");
      out.write("        <div class=\"grid\">\r\n");
      out.write("            <div class=\"card\"><i class=\"fa-solid fa-network-wired\"></i>RMI fundamentals</div>\r\n");
      out.write("            <div class=\"card\"><i class=\"fa-solid fa-diagram-project\"></i>RMI architecture</div>\r\n");
      out.write("            <div class=\"card\"><i class=\"fa-solid fa-box\"></i>Serialization</div>\r\n");
      out.write("            <div class=\"card\"><i class=\"fa-solid fa-code\"></i>Build RMI applications</div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("\r\n");
      out.write("    <section data-aos=\"fade-up\">\r\n");
      out.write("        <h2>What is Java RMI?</h2>\r\n");
      out.write("        <p>Java RMI enables method invocation on objects residing in different JVMs. It abstracts socket-level communication while preserving object-oriented semantics.</p>\r\n");
      out.write("    </section>\r\n");
      out.write("\r\n");
      out.write("    <section data-aos=\"fade-up\">\r\n");
      out.write("        <h2>RMI Components</h2>\r\n");
      out.write("        <div class=\"grid\">\r\n");
      out.write("            <div class=\"card\"><i class=\"fa-solid fa-server\"></i><b>Server</b><br>Hosts and registers remote objects</div>\r\n");
      out.write("            <div class=\"card\"><i class=\"fa-solid fa-database\"></i><b>Registry</b><br>Maps names to stubs</div>\r\n");
      out.write("            <div class=\"card\"><i class=\"fa-solid fa-laptop-code\"></i><b>Client</b><br>Invokes remote methods</div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("\r\n");
      out.write("    <section data-aos=\"fade-up\">\r\n");
      out.write("        <h2>Serialization</h2>\r\n");
      out.write("        <p>Serialization converts objects into byte streams for network transfer. Classes must implement <code>Serializable</code>.</p>\r\n");
      out.write("    </section>\r\n");
      out.write("\r\n");
      out.write("    <section data-aos=\"fade-up\">\r\n");
      out.write("        <h2>RMI Development Steps</h2>\r\n");
      out.write("        <div class=\"grid\">\r\n");
      out.write("            <div class=\"step\">1. Define remote interface</div>\r\n");
      out.write("            <div class=\"step\">2. Implement remote object</div>\r\n");
      out.write("            <div class=\"step\">3. Create client</div>\r\n");
      out.write("            <div class=\"step\">4. Compile & generate stubs</div>\r\n");
      out.write("            <div class=\"step\">5. Start registry</div>\r\n");
      out.write("            <div class=\"step\">6. Run server & client</div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<footer>\r\n");
      out.write("    © 2025 · Distributed Programming · Servlet-Based LMS\r\n");
      out.write("</footer>\r\n");
      out.write("\r\n");
      out.write("<script src=\"https://unpkg.com/aos@2.3.1/dist/aos.js\"></script>\r\n");
      out.write("<script>AOS.init({ once: true, duration: 900 });</script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
