/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/11.0.4
 * Generated at: 2026-01-18 16:48:07 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <title>Advanced Programming LMS</title>\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Icons -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Font -->\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Inter:wght@300;400;600;700&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <!-- AOS -->\r\n");
      out.write("    <link href=\"https://unpkg.com/aos@2.3.1/dist/aos.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <style>\r\n");
      out.write("        * { box-sizing: border-box; }\r\n");
      out.write("        body {\r\n");
      out.write("            margin: 0;\r\n");
      out.write("            font-family: 'Inter', sans-serif;\r\n");
      out.write("            background: radial-gradient(circle at top, #2563eb55, transparent 60%), #020617;\r\n");
      out.write("            color: #e5e7eb;\r\n");
      out.write("        }\r\n");
      out.write("        header {\r\n");
      out.write("            padding: 2rem 3rem;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            justify-content: space-between;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            background: rgba(15, 23, 42, 0.85);\r\n");
      out.write("            backdrop-filter: blur(10px);\r\n");
      out.write("            position: sticky;\r\n");
      out.write("            top: 0;\r\n");
      out.write("            z-index: 10;\r\n");
      out.write("        }\r\n");
      out.write("        header h1 { font-size: 1.5rem; }\r\n");
      out.write("        header nav a {\r\n");
      out.write("            margin-left: 1.5rem;\r\n");
      out.write("            color: #c7d2fe;\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("            font-weight: 500;\r\n");
      out.write("        }\r\n");
      out.write("        .hero {\r\n");
      out.write("            padding: 6rem 3rem;\r\n");
      out.write("            max-width: 1200px;\r\n");
      out.write("            margin: auto;\r\n");
      out.write("        }\r\n");
      out.write("        .hero h2 {\r\n");
      out.write("            font-size: 3.2rem;\r\n");
      out.write("            font-weight: 700;\r\n");
      out.write("            line-height: 1.2;\r\n");
      out.write("        }\r\n");
      out.write("        .hero p {\r\n");
      out.write("            max-width: 600px;\r\n");
      out.write("            color: #94a3b8;\r\n");
      out.write("            margin-top: 1.5rem;\r\n");
      out.write("        }\r\n");
      out.write("        .hero button {\r\n");
      out.write("            margin-top: 2rem;\r\n");
      out.write("            padding: 0.9rem 1.5rem;\r\n");
      out.write("            border-radius: 14px;\r\n");
      out.write("            border: none;\r\n");
      out.write("            background: linear-gradient(135deg, #2563eb, #3b82f6);\r\n");
      out.write("            color: #fff;\r\n");
      out.write("            font-weight: 600;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("        }\r\n");
      out.write("        .section {\r\n");
      out.write("            max-width: 1200px;\r\n");
      out.write("            margin: auto;\r\n");
      out.write("            padding: 4rem 3rem;\r\n");
      out.write("        }\r\n");
      out.write("        .section h3 { font-size: 2.2rem; margin-bottom: 2rem; }\r\n");
      out.write("        .grid {\r\n");
      out.write("            display: grid;\r\n");
      out.write("            grid-template-columns: repeat(auto-fit, minmax(260px, 1fr));\r\n");
      out.write("            gap: 1.8rem;\r\n");
      out.write("        }\r\n");
      out.write("        .card {\r\n");
      out.write("            background: rgba(15, 23, 42, 0.85);\r\n");
      out.write("            border-radius: 20px;\r\n");
      out.write("            padding: 2rem;\r\n");
      out.write("            box-shadow: 0 30px 60px rgba(0,0,0,0.6);\r\n");
      out.write("            transition: transform .3s ease;\r\n");
      out.write("        }\r\n");
      out.write("        .card:hover { transform: translateY(-10px); }\r\n");
      out.write("        .card i {\r\n");
      out.write("            font-size: 2.2rem;\r\n");
      out.write("            color: #60a5fa;\r\n");
      out.write("            margin-bottom: 1rem;\r\n");
      out.write("        }\r\n");
      out.write("        .card span {\r\n");
      out.write("            display: block;\r\n");
      out.write("            margin-top: 0.8rem;\r\n");
      out.write("            color: #94a3b8;\r\n");
      out.write("            font-size: 0.9rem;\r\n");
      out.write("        }\r\n");
      out.write("        footer {\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            padding: 2rem;\r\n");
      out.write("            color: #64748b;\r\n");
      out.write("            font-size: .9rem;\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<header>\r\n");
      out.write("    <h1><i class=\"fa-solid fa-graduation-cap\"></i> Advanced Programming</h1>\r\n");
      out.write("    <nav>\r\n");
      out.write("        <a href=\"index.jsp\">Home</a>\r\n");
      out.write("        <a href=\"NetworkProgramming.jsp\">NetworkProgramming</a>\r\n");
      out.write("        <a href=\"DistributedProgramming.jsp\">DistributedProgramming</a>\r\n");
      out.write("        <a href=\"online.jsp\">Online Compiler</a>\r\n");
      out.write("        <a href=\"logout\">Logout</a>\r\n");
      out.write("    </nav>\r\n");
      out.write("</header>\r\n");
      out.write("\r\n");
      out.write("<section class=\"hero\" data-aos=\"fade-up\">\r\n");
      out.write("    <h2>Build. Compile. Distribute.<br>Advanced Java Programming</h2>\r\n");
      out.write("    <p>\r\n");
      out.write("        Master network programming, distributed systems, and real-world Java technologies\r\n");
      out.write("        with interactive labs and an online compiler.\r\n");
      out.write("    </p>\r\n");
      out.write("    <button onclick=\"location.href='chapter4'\">\r\n");
      out.write("        <i class=\"fa-solid fa-rocket\"></i> Start Learning\r\n");
      out.write("    </button>\r\n");
      out.write("</section>\r\n");
      out.write("\r\n");
      out.write("<section class=\"section\" data-aos=\"fade-up\">\r\n");
      out.write("    <h3>Course Chapters</h3>\r\n");
      out.write("    <div class=\"grid\">\r\n");
      out.write("        <div class=\"card\" onclick=\"location.href='chapter4'\">\r\n");
      out.write("            <i class=\"fa-solid fa-network-wired\"></i>\r\n");
      out.write("            <b>Chapter 4</b>\r\n");
      out.write("            <span>Network Programming & Sockets</span>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"card\" onclick=\"location.href='chapter5'\">\r\n");
      out.write("            <i class=\"fa-solid fa-diagram-project\"></i>\r\n");
      out.write("            <b>Chapter 5</b>\r\n");
      out.write("            <span>Distributed Programming (RMI)</span>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</section>\r\n");
      out.write("\r\n");
      out.write("<section class=\"section\" data-aos=\"fade-up\">\r\n");
      out.write("    <h3>Hands-on Labs</h3>\r\n");
      out.write("    <div class=\"grid\">\r\n");
      out.write("        <div class=\"card\">\r\n");
      out.write("            <i class=\"fa-solid fa-flask\"></i>\r\n");
      out.write("            <b>Socket Programming Lab</b>\r\n");
      out.write("            <span>TCP/UDP client-server practice</span>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"card\">\r\n");
      out.write("            <i class=\"fa-solid fa-flask-vial\"></i>\r\n");
      out.write("            <b>RMI Lab</b>\r\n");
      out.write("            <span>Build distributed Java applications</span>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</section>\r\n");
      out.write("\r\n");
      out.write("<section class=\"section\" data-aos=\"fade-up\">\r\n");
      out.write("    <h3>Online Compiler</h3>\r\n");
      out.write("    <div class=\"grid\">\r\n");
      out.write("        <div class=\"card\">\r\n");
      out.write("            <i class=\"fa-solid fa-terminal\"></i>\r\n");
      out.write("            <b>Java Online Compiler</b>\r\n");
      out.write("            <span>Write, compile, and run Java code directly in the browser</span>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</section>\r\n");
      out.write("\r\n");
      out.write("<footer>\r\n");
      out.write("    © 2025 · Advanced Programming  · Servlet Based Platform\r\n");
      out.write("</footer>\r\n");
      out.write("\r\n");
      out.write("<script src=\"https://unpkg.com/aos@2.3.1/dist/aos.js\"></script>\r\n");
      out.write("<script>AOS.init({ once: true, duration: 900 });</script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
