/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/11.0.4
 * Generated at: 2026-01-14 23:15:08 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class online_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <title>Online Compiler | Advanced Programming LMS</title>\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("\n");
      out.write("    <!-- Icons -->\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css\">\n");
      out.write("\n");
      out.write("    <!-- Font -->\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Inter:wght@300;400;600;700&display=swap\" rel=\"stylesheet\">\n");
      out.write("\n");
      out.write("    <!-- AOS -->\n");
      out.write("    <link href=\"https://unpkg.com/aos@2.3.1/dist/aos.css\" rel=\"stylesheet\">\n");
      out.write("\n");
      out.write("    <style>\n");
      out.write("        * { box-sizing: border-box; }\n");
      out.write("\n");
      out.write("        body {\n");
      out.write("            margin: 0;\n");
      out.write("            font-family: 'Inter', sans-serif;\n");
      out.write("            background: radial-gradient(circle at top, #22d3ee55, transparent 60%), #020617;\n");
      out.write("            color: #e5e7eb;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        header {\n");
      out.write("            padding: 1.8rem 3rem;\n");
      out.write("            display: flex;\n");
      out.write("            justify-content: space-between;\n");
      out.write("            align-items: center;\n");
      out.write("            background: rgba(15, 23, 42, 0.85);\n");
      out.write("            backdrop-filter: blur(10px);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        header h1 {\n");
      out.write("            font-size: 1.4rem;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        header a {\n");
      out.write("            color: #c7d2fe;\n");
      out.write("            text-decoration: none;\n");
      out.write("            margin-left: 1.5rem;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .container {\n");
      out.write("            max-width: 1400px;\n");
      out.write("            margin: auto;\n");
      out.write("            padding: 3rem;\n");
      out.write("            display: grid;\n");
      out.write("            grid-template-columns: 2fr 1fr;\n");
      out.write("            gap: 2rem;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .panel {\n");
      out.write("            background: rgba(15, 23, 42, 0.9);\n");
      out.write("            border-radius: 20px;\n");
      out.write("            padding: 1.8rem;\n");
      out.write("            box-shadow: 0 30px 60px rgba(0,0,0,0.6);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        textarea {\n");
      out.write("            width: 100%;\n");
      out.write("            height: 420px;\n");
      out.write("            background: #020617;\n");
      out.write("            border: none;\n");
      out.write("            border-radius: 14px;\n");
      out.write("            color: #e5e7eb;\n");
      out.write("            padding: 1rem;\n");
      out.write("            font-family: monospace;\n");
      out.write("            font-size: 0.95rem;\n");
      out.write("            resize: none;\n");
      out.write("            outline: none;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        select, button {\n");
      out.write("            width: 100%;\n");
      out.write("            padding: 0.9rem;\n");
      out.write("            border-radius: 12px;\n");
      out.write("            border: none;\n");
      out.write("            margin-top: 1rem;\n");
      out.write("            font-weight: 600;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        select {\n");
      out.write("            background: #020617;\n");
      out.write("            color: #e5e7eb;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        button {\n");
      out.write("            background: linear-gradient(135deg, #22d3ee, #3b82f6);\n");
      out.write("            color: #020617;\n");
      out.write("            cursor: pointer;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        pre {\n");
      out.write("            background: #020617;\n");
      out.write("            padding: 1rem;\n");
      out.write("            border-radius: 14px;\n");
      out.write("            height: 420px;\n");
      out.write("            overflow-y: auto;\n");
      out.write("            font-size: 0.9rem;\n");
      out.write("            white-space: pre-wrap;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        footer {\n");
      out.write("            text-align: center;\n");
      out.write("            padding: 1.5rem;\n");
      out.write("            color: #64748b;\n");
      out.write("            font-size: .9rem;\n");
      out.write("        }\n");
      out.write("    </style>\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("<header>\n");
      out.write("    <h1><i class=\"fa-solid fa-terminal\"></i> Online Compiler</h1>\n");
      out.write("    <nav>\n");
      out.write("        <a href=\"index.jsp\">Home</a>\n");
      out.write("        <a href=\"compile\">Compiler</a>\n");
      out.write("        <a href=\"logout\">Logout</a>\n");
      out.write("    </nav>\n");
      out.write("</header>\n");
      out.write("\n");
      out.write("<div class=\"container\" data-aos=\"fade-up\">\n");
      out.write("\n");
      out.write("    <!-- LEFT: CODE EDITOR -->\n");
      out.write("    <div class=\"panel\">\n");
      out.write("        <h3><i class=\"fa-solid fa-code\"></i> Code Editor</h3>\n");
      out.write("\n");
      out.write("        <form method=\"post\" action=\"compile\">\n");
      out.write("\n");
      out.write("            <textarea name=\"code\" required>");

                String code = (String) request.getAttribute("code");
                if (code != null) {
                    out.print(code);
                } else {
            
      out.write("\n");
      out.write("public class Main {\n");
      out.write("    public static void main(String[] args) {\n");
      out.write("        System.out.println(\"Hello from Compiler\");\n");
      out.write("    }\n");
      out.write("}\n");

                }
            
      out.write("</textarea>\n");
      out.write("\n");
      out.write("            <select name=\"language\" required>\n");
      out.write("                <option value=\"java\"\n");
      out.write("                    ");
      out.print( "java".equals(request.getAttribute("language")) ? "selected" : "" );
      out.write(">\n");
      out.write("                    Java\n");
      out.write("                </option>\n");
      out.write("                <option value=\"python\"\n");
      out.write("                    ");
      out.print( "python".equals(request.getAttribute("language")) ? "selected" : "" );
      out.write(">\n");
      out.write("                    Python\n");
      out.write("                </option>\n");
      out.write("                <option value=\"javascript\"\n");
      out.write("                    ");
      out.print( "javascript".equals(request.getAttribute("language")) ? "selected" : "" );
      out.write(">\n");
      out.write("                    JavaScript\n");
      out.write("                </option>\n");
      out.write("            </select>\n");
      out.write("\n");
      out.write("            <button type=\"submit\">\n");
      out.write("                <i class=\"fa-solid fa-play\"></i> Run Code\n");
      out.write("            </button>\n");
      out.write("        </form>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <!-- RIGHT: OUTPUT -->\n");
      out.write("    <div class=\"panel\">\n");
      out.write("        <h3><i class=\"fa-solid fa-bug\"></i> Output</h3>\n");
      out.write("        <pre>");

            String output = (String) request.getAttribute("output");
            if (output != null) {
                out.print(output+"\n done");
            } else {
                out.print("Program output will appear here...");
            }
        
      out.write("</pre>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<footer>\n");
      out.write("    © 2025 · Advanced Programming LMS · Secure Docker-Based Compiler\n");
      out.write("</footer>\n");
      out.write("\n");
      out.write("<script src=\"https://unpkg.com/aos@2.3.1/dist/aos.js\"></script>\n");
      out.write("<script>\n");
      out.write("    AOS.init({ once: true, duration: 900 });\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
