/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/11.0.4
 * Generated at: 2026-01-18 16:48:23 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class register_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <title>Register | E‑Learning </title>\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css\">\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Inter:wght@300;400;600;700&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"https://unpkg.com/aos@2.3.1/dist/aos.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <style>\r\n");
      out.write("        * { box-sizing: border-box; }\r\n");
      out.write("        body {\r\n");
      out.write("            margin: 0;\r\n");
      out.write("            font-family: 'Inter', sans-serif;\r\n");
      out.write("            background: radial-gradient(circle at top, #2563eb55, transparent 60%), #020617;\r\n");
      out.write("            color: #e5e7eb;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            justify-content: center;\r\n");
      out.write("            min-height: 100vh;\r\n");
      out.write("        }\r\n");
      out.write("        .auth-card {\r\n");
      out.write("            width: 420px;\r\n");
      out.write("            background: rgba(15, 23, 42, 0.9);\r\n");
      out.write("            border-radius: 20px;\r\n");
      out.write("            padding: 2.5rem;\r\n");
      out.write("            box-shadow: 0 30px 60px rgba(0,0,0,0.6);\r\n");
      out.write("        }\r\n");
      out.write("        .auth-card h1 {\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            margin-bottom: 0.5rem;\r\n");
      out.write("        }\r\n");
      out.write("        .auth-card p {\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            color: #94a3b8;\r\n");
      out.write("            margin-bottom: 2rem;\r\n");
      out.write("        }\r\n");
      out.write("        .field {\r\n");
      out.write("            position: relative;\r\n");
      out.write("            margin-bottom: 1.5rem;\r\n");
      out.write("        }\r\n");
      out.write("        .field i {\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            top: 50%;\r\n");
      out.write("            left: 15px;\r\n");
      out.write("            transform: translateY(-50%);\r\n");
      out.write("            color: #60a5fa;\r\n");
      out.write("        }\r\n");
      out.write("        .field input {\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            padding: 0.9rem 0.9rem 0.9rem 2.8rem;\r\n");
      out.write("            border-radius: 12px;\r\n");
      out.write("            border: none;\r\n");
      out.write("            background: #020617;\r\n");
      out.write("            color: #e5e7eb;\r\n");
      out.write("            outline: none;\r\n");
      out.write("        }\r\n");
      out.write("        .field input:focus {\r\n");
      out.write("            box-shadow: 0 0 0 2px #3b82f6;\r\n");
      out.write("        }\r\n");
      out.write("        button {\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            padding: 0.9rem;\r\n");
      out.write("            border-radius: 12px;\r\n");
      out.write("            border: none;\r\n");
      out.write("            background: linear-gradient(135deg, #2563eb, #3b82f6);\r\n");
      out.write("            color: #fff;\r\n");
      out.write("            font-weight: 600;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("            margin-top: 1rem;\r\n");
      out.write("        }\r\n");
      out.write("        button:hover { opacity: 0.9; }\r\n");
      out.write("        .switch {\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            margin-top: 1.5rem;\r\n");
      out.write("            font-size: 0.9rem;\r\n");
      out.write("        }\r\n");
      out.write("        .switch a { color: #60a5fa; text-decoration: none; }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<div class=\"auth-card\" data-aos=\"zoom-in\">\r\n");
      out.write("    <h1><i class=\"fa-solid fa-user-plus\"></i> Create Account</h1>\r\n");
      out.write("    <p>Join the e‑learning platform</p>\r\n");
      out.write("\r\n");
      out.write("    <form method=\"post\" action=\"register\">\r\n");
      out.write("        <div class=\"field\">\r\n");
      out.write("            <i class=\"fa-solid fa-user\"></i>\r\n");
      out.write("            <input type=\"text\" name=\"FirstName\" placeholder=\"First Name\" required>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"field\">\r\n");
      out.write("            <i class=\"fa-solid fa-user\"></i>\r\n");
      out.write("            <input type=\"text\" name=\"LastName\" placeholder=\"Last Name\" required>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"field\">\r\n");
      out.write("            <i class=\"fa-solid fa-envelope\"></i>\r\n");
      out.write("            <input type=\"email\" name=\"email\" placeholder=\"Email address\" required>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"field\">\r\n");
      out.write("            <i class=\"fa-solid fa-lock\"></i>\r\n");
      out.write("            <input type=\"password\" name=\"Password\" placeholder=\"Password\" required>\r\n");
      out.write("        </div>\r\n");
      out.write("        <button type=\"submit\"><i class=\"fa-solid fa-user-check\"></i> Register</button>\r\n");
      out.write("    </form>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"switch\">\r\n");
      out.write("        Already registered? <a href=\"login.jsp\">Login</a>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<script src=\"https://unpkg.com/aos@2.3.1/dist/aos.js\"></script>\r\n");
      out.write("<script>AOS.init({ once: true, duration: 900 });</script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
